var res = {
    helloBG_png : "res/helloBG.png",
    start_n_png : "res/start_n.png",
    start_s_png : "res/start_s.png",
    PlayBG_png  : "res/PlayBG.png",
    box_png  : "res/box.png",
    runner_plist : "res/running.plist",
    map_png : "res/map.png",
    map00_tmx : "res/map00.tmx",
    map01_tmx : "res/map01.tmx",
    background_png :"res/background.png",
    background_plist : "res/background.plist",
    restart_n_png : "res/restart_n.png",
    restart_s_png : "res/restart_s.png",
    wall_png : "res/wall.png",
    cir_png : "res/cir.png",
    poly3_png : "res/poly3.png",
    rectangle_png:"res/Rectangle.png",
};

var g_resources = [
    //image
    res.helloBG_png,
    res.start_n_png,
    res.start_s_png,
    res.PlayBG_png,
    res.box_png,
    res.runner_plist,
    res.map_png,
    res.map00_tmx,
    res.map01_tmx,
    res.background_png,
    res.background_plist,
    res.restart_n_png,
    res.restart_s_png,
    res.wall_png,
    res.cir_png,
    res.poly3_png,
    res.rectangle_png,
];